language: bash

services:
    - docker

script:
    - docker run --rm -i \
      -v $(pwd):/src \
      klakegg/hugo:0.73.0 \
      build -D --gc

script:
  - hugo --theme=basics --buildDrafts

# deploy:
#  - provider: s3
#  - access_key_id: "YOUR AWS ACCESS KEY"
#  - secret_access_key: "YOUR AWS SECRET KEY"
#  - bucket: "S3 Bucket"
#  - skip_cleanup: true
#  - local_dir: build
