baseURL = "/"
languageCode = "en-us"
title = "My Projects"
relativeURLS = true
googleAnalytics = "UA-129701467-1"

[params]
    author = "Max Hoffman"
    github = "max-hoffman"
    linkedin = "max-hoffman-04790aa6"
    styles = ["css/styles.css"]
