baseURL = "/"
languageCode = "en-us"
title = "Max Hoffman's Personal Site"
relativeURLS = true

[params]
    author = "Max Hoffman"
    github = "max-hoffman"
    linkedin = "max-hoffman-04790aa6"
    styles = ["css/styles.css"]
